- name: Download k3sup
  get_url:
    url: https://get.k3sup.dev 
    dest: "{{ k3sup_download_location }}"

- name: Bootstrap k3sup
  command: sh "{{ k3sup_download_location }}"

- name: Clean up download
  file: 
    path: "{{ k3sup_download_location }}"
    state: absent
  
- name: Copy to bin
  become: yes
  copy:
    src: k3sup-arm64
    dest: /usr/local/bin/k3sup
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=rx,o=r

- name: Delete local k3sup, now it's in /usr/local/bin
  file: 
    path: k3sup-arm64
    state: absent

- name: Load master key (so we can use it in the next step)
  slurp:
    src: '.ssh/id_rsa.pub'
  register: master_key

- name: Authorize self to SSH to self (authorise own key)
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ master_key['content'] | b64decode }}"
    path: "/home/ubuntu/.ssh/authorized_keys"


- name: Install master node - k3sup
  become: yes
  become_method: sudo
  command: "k3sup install --local --k3s-version={{ version }} --k3s-extra-args '--no-deploy traefik'" # install without traefik do we can use nginx for ingress
  
- name: Make config file readable by ubuntu so we can run kubectl without sudo
  become: yes
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: ubuntu
    group: ubuntu

- name: Configure the location of the kubeconfig file so that Helm doesn't shit the bed
  shell: "echo export KUBECONFIG=/etc/rancher/k3s/k3s.yaml > .bash_profile"
    