# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo update

# helm install [RELEASE_NAME] prometheus-community/kube-prometheus-stack

# kubectl create namespace monitoring
# helm install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring


- name: Add the monitoring namespace
  shell: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

- name: Install the prometheus chart
  shell: helm upgrade --install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring # use upgrade rather than install for idempotency
  environment: 
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  