- name: Please update secrets.yaml with the base64 encoded key from entrydns.net/cloudflare.com (get the token and pase into www.base64encode.org), then manually update the secrets file
  pause:
    prompt: Please hit [ENTER] once you have configured the secrets yaml

# Commented out because not actually using CF ATM
# - name: Cloudflare DNS (catholicon.uk)
#   command: kubectl apply -f repos/cloudflare_dns/{{ item }}.yaml
#   with_items:
#   - namespace
#   - secret
#   - configmap
#   - pod


- name: EntryDNS (rdomloge.entrydns.org)
  command: kubectl apply -f repos/entrydns/{{ item }}.yaml
  with_items:
  - namespace
  - secret
  - cron