- name: Check if Arkade is already installed
  stat:
    path: /usr/local/bin/arkade
  register: arkade

- name: Download Arkade
  when: arkade.stat.exists == false
  get_url: 
    url: https://get.arkade.dev 
    dest: "{{ arkade_installer }}"
    mode: 775

- name: Install Arkade
  when: arkade.stat.exists == false
  become: true
  command: "{{ arkade_installer }}"

- name: Delete Arkade installer
  when: arkade.stat.exists == false
  file: 
    path: "{{ arkade_installer }}"
    state: absent

- name: Install OpenFaas
  command: arkade install openfaas --gateways 2 --load-balancer false --set faasIdler.dryRun=false
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  async: 2000
  poll: 0
  register: of_install_progress

- name: Wait for OpenFaas install
  async_status:
    jid: "{{ of_install_progress.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
  delay: 5

- name: Print out admin password
  shell: 'echo $(kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode)'

- name: Pause for capture of admin password just printed out
  pause:
    prompt: Please hit [ENTER] once you have copied the admin password above