---

- hosts: master
  gather_facts: false
  tasks:
  - name: Printout master pubkey
    shell: |
      cat /home/ubuntu/.ssh/id_rsa.pub

- hosts: master
  gather_facts: false
  tasks:
  - name: Wait for user prompt to continue (once GitHub is ready)
    pause:
      prompt: Please hit [ENTER] once you have configured the key above in GitHub

- name: Clone repos
  hosts: master  
  vars_files:
  - vars.yml
  tasks:
    - import_tasks: repos.yaml

- name: Run catholicon
  hosts: master  
  vars_files:
  - vars.yml
  tasks:
    - import_tasks: catholicon.yaml

# - name: Helium
#   hosts: master
#   vars_files:
#   - vars.yml
#   tasks:
#     - import_tasks: helium.yaml

- name: Bobcat rebooter
  hosts: master
  vars_files:
  - vars.yml
  tasks:
    - import_tasks: bobcat-rebooter.yaml

- name: Minecraft
  hosts: master
  vars_files:
  - vars.yml
  tasks:
    - import_tasks: minecraft.yaml

- name: OpenFaaS
  hosts: master
  vars_files:
  - vars.yml
  tasks:
    - import_tasks: openfaas.yaml

- name: DNS
  hosts: master
  vars_files:
  - vars.yml
  tasks:
    - import_tasks: dns.yaml

- name: Cert Manager
  hosts: master
  vars_files:
  - vars.yml
  tasks:
    - import_tasks: cert-manager.yaml